# Generated by Django 2.0.1 on 2018-01-31 15:32

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180127_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
